---
# Comrpbamos si el directorio del blog existe
- name: Comprobar instalacion wordpress
  stat: path=/var/www/html/{{ blog_dir }}
  register: blog_path

# Descargamos Wordpress 
- name: Descargamos Wordpress
  get_url: url=http://es.wordpress.org/wordpress-{{ wp_version }}-es_ES.tar.gz dest=/tmp
  when: blog_path.stat.exists == false

# Descomprimimos wordpress
- name: Extraemos ficheros de Wordpress
  command: chdir=/var/www/html/ /bin/tar xvf wordpress-{{ wp_version }}-es_ES.tar.gz creates=/tmp/wordpress
  when: blog_path.stat.exists == false

#Eliminamos el comprimido
- name: Eliminamos .tar.gz de wordpress
  command: chdir=/var/www/html rm wordpress-{{ wp_version }}-es_ES.tar.gz
  when: blog_path.stat.exists == false

#Movemos el directorio Wordpress a su sitio
- name: Movemos el directorio wordpress a www
  command: chdir=/tmp mv wordpress /var/www/html/{{ blog_dir }} creates=/var/www/html/{{ blog_dir }}
  when: blog_path.stat.exists == false

#Creamos la base de datos de wordpress
- name: Crear base de datos Wordpress
  mysql_db: name={{ wp_db_blog }} state=present

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

 #Creamos usuarios en la base de datos de Wordpress
- name: Creamos usuario para la base de datos de Wordpress
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_priv }}.*:ALL host='localhost' state=present

 #Copiamos el fichero de configuraci贸n de Wordpress
- name: Copiamos el fichero de configuraci贸n de wordpress
  template: src=wp-config.php dest=/var/www/html/{{ blog_dir }}/

#Cambiar permisos de la instalacion de wordpress
- name: Cambiar permisos de la instalaci贸n wordpress
  file: path=/var/www/html/{{ blog_dir }} owner=www-data group=www-data state=directory recurse=yes

# Deshabilitar sitio por defecto de Apache2
- name: deshabilitar sitio por defecto de Apache2
  command: a2dissite 000-default

# Copiamos el sitio de Apache que contiene la configuraci贸n que apunta a nuestro blog
- name: copiar sitio apache del blog
  template: src=wordpress.conf dest=/etc/apache2/sites-available/{{ blog_dir }}.conf

# Habilitamos el sitio del blog
- name: habilitar site del blog
  command: a2ensite {{ blog_dir }}
  notify: reiniciar apache2