# Indicamos que las tareas del playbook se ejecutarán en todas las máquinas
- hosts: all
# Se usará sudo para ejecutar los comandos que lo requieran
  sudo: yes
# Empezamos a definir las tareas a ejecutar
  roles:
    - common
    - webserver
    - mysql