# Indicamos que las tareas del playbook se ejecutarán en todas las máquinas
- hosts: web
# Se usará sudo para ejecutar los comandos que lo requieran
  sudo: yes
# Empezamos a definir las tareas a ejecutar
  roles:
    - common
    - webserver
    - mysql
    - blog

- hosts: dns
  sudo: yes
  roles:
   - common
   - dns